---
'en':
      :welcome: 'Welcome to Loan Calculator! Enter Your Name:'
      :loan_amount: What's the total loan amount?
      :loan_duration: What's the total loan duration (in Years)?
      :loan_rate: What's the total loan interest rate (Annual)?
      :valid_name: Make sure to enter a valid name
      :valid_loan_amt: Make sure to enter a valid loan amount
      :valid_loan_dur: Make sure to enter a valid loan duration
      :valid_loan_rate: Make sure to enter a valid loan rate
      :operator_prompt: |2
            What is the operation to perform
            1) Addition
            2) Subtraction
            3) Multiplication
            4) Division
      :valid_operator: Please enter a valid operator from the given options
      :continue: Type Y if you want to continue using the calculator
