---
'en':
      :welcome: 'Welcome to Calculator! Enter Your Name:'
      :num1_prompt: What's the first number?
      :num2_prompt: What's the second number?
      :valid_name: Make sure to enter a valid name
      :valid_number: Hmm that doesn't look like a valid number
      :operator_prompt: |2
            What is the operation to perform
            1) Addition
            2) Subtraction
            3) Multiplication
            4) Division
      :valid_operator: Please enter a valid operator from the given options
      :continue: Type Y if you want to continue using the calculator
